### ISSUE TITLE
ThunderStats! does not update for my IMAP accounts

### ISSUE THREAD

**Issue by emilmajkowski** [micz/ThunderStats#131] opened 2016-08-24 12:08 UTC
Hello,

I have few quite a big IMAP accounts with multiple folders. After installing the add-on I see it working but no stats show up. 
It shows only
Total mails in the inbox: 13220Loading...    unread: 5735Loading...
But there is no charts displayed nor detais

Could you please advice what can be the issue or how I can debug it?
Thank you
Emil

**Comment by micz** [comment] 2016-08-26 19:28
Hi Emil,

may you try this?

1. Close ThunderStats tab
2. Press Crtl+Shift+J, it opens the error console.
3. Clear the console
4. Open ThunderStats
5. Check if in the console there are errors or warnings.

Thank you.

**Comment by emilmajkowski** [comment] 2016-08-28 05:55
Thank you.
There is an error in the error console that some script is blocked internally. Could you please let me know how I can unblock it?
Please see attached screen

![image](https://cloud.githubusercontent.com/assets/21219279/18031918/c224674a-6cf4-11e6-9a87-628c98e6c698.png)

Thank you!
Emil

**Comment by micz** [comment] 2016-08-28 09:18
Which is your Thunderbird version?

**Comment by emilmajkowski** [comment] 2016-08-29 09:33
My Thunderbird is 45.2.0 version

**Comment by emilmajkowski** [comment] 2016-08-30 06:39
I can see a lot of errors in the Errors console. Could you please advice?
![screen shot 2016-08-30 at 08 38 36](https://cloud.githubusercontent.com/assets/21219279/18078688/37e5983e-6e8d-11e6-98f2-4aa62eaf08ca.png)

**Comment by micz** [comment] 2016-08-30 06:55
Those errors should not be related to ThunderStats. Do you see them also with ThunderStats tab closed?
In regard to the previous error message, I'm sorry, I was stil not able to reproduce them.
I'll came back as soon as possibile.

**Comment by emilmajkowski** [comment] 2016-08-30 11:55
You are right, these errors appear also without thunderStats switched on

**Comment by micz** [comment] 2016-09-22 18:23
I'm sorry, I was not able to replicate your problem.
Do you have a very big number of emails? Have you tried to wait a few minutes to let the stats compute?

Otherwise, if you feel confident, you could try to forse Thunderbird to rebuild the index, as described here: https://support.mozilla.org/en-US/kb/rebuilding-global-database

**Comment by DrQuixote** [comment] 2016-11-11 18:30
Hello micz!
I have the same problem as described above (no update for imap accounts).  My version is 45.4.0.
You can find the error below.
I'm just rebuilding the database. As it is building since 10 minutes and doesn't stop,
I will now get into my well-earned weekend and report on monday if the problem has been solved or not ;).

Cheers and thanks a lot.
Julian (who looks very much forward to the addon - if it does work ;))

![screenshot](https://cloud.githubusercontent.com/assets/23406220/20225224/7c686c36-a842-11e6-9313-d7a68d849c71.jpg)

**Comment by DrQuixote** [comment] 2016-11-11 18:52
Ok, it was faster than expected. The database finished rebuilding now. 
However, the issue persists. When I click on update it seems the program trys to find something but than says: no emails sent no emails received :/.
Would be extremely happy about a fix!

Best
Julian

**Comment by micz** [comment] 2016-11-11 19:09
Hello Julian,

please activate the debug system from here:

![164704](https://cloud.githubusercontent.com/assets/61795/20226891/3d24c788-a84a-11e6-9c14-d195777d8fc5.jpg)

Then may you tell me if there are more messages in the console?
How may accounts/email addresses do you have in your installation? Are you filtering a particular email address?

May you also try a "Custom View" query checking the "Business day only flag"?

Thank you.

**Comment by micz** [comment] 2016-11-13 22:22
I've developed a tool to help debug those problems on a new version of ThunderStats (english only).

You can download it from here: 

https://dl.dropboxusercontent.com/u/109379940/ThunderStats-1.3alpha.xpi

On the preference window click on the "Run the debugger" button.

![1](https://cloud.githubusercontent.com/assets/61795/20249336/b95bb5f6-a9f7-11e6-9284-a114fece8027.jpg)

Then on the debugger window, after it says "Completed!" on the top, click the "Send report" button on the bottom.

![2](https://cloud.githubusercontent.com/assets/61795/20249340/bea7e890-a9f7-11e6-9c8c-ab6abe4da87a.jpg)

This will open a mail message with the report in it. You can send it to me.

Thank you.

**Comment by DrQuixote** [comment] 2016-11-30 15:35
Dear micz,
thank you very much for your fast answers. I will try your suggestions as soon as possible. Atm my office has developed a huge prechristmasstress, hence I couldn't try them out, yet. But it is not forgotten!

Best
DQ

**Comment by micz** [comment] 2016-11-30 22:33
Version 1.3 is going to be officially released, so you could wait for it without the need to install that alpha version.
Running the debugger is than just a matter of a couple of clicks.
Thank you.

**Comment by mistretta** [comment] 2017-01-22 20:32
Got exactly the same issue, the only mail that appears in stats is the one I sent you with the debug informations

**Comment by micz** [comment] 2017-01-22 22:16
I received your debug report, thank you. I replied to it a moment ago.

Please follow the instruction I reported there, may be your problem is due to the Thunderbird indexing.
You should force Thunderbird to rebuild its entire internal database, as described here: https://support.mozilla.org/en-US/kb/rebuilding-global-database
Try this option only if you're confident in what you are doing, because you could damage your data. Do always a backup before.

**Comment by micz** [comment] 2017-01-23 21:20
**From version 1.3 the debugger report is available for every user.**
I received many reports from various users (many thanks to all!) and it seems that all the problems are not directly related to this extension.

Mainly the problems are:
1. **Thunderbird indexing is not working or is stuck for some reason.** To fix this problem follow this instructions to rebuild Thunderbird's internal database: https://support.mozilla.org/en-US/kb/rebuilding-global-database
2. **Account mail address misspelled.** The email address must be written with NO CAPITOL letters, otherwise Thunderbird is not saving correctly the sent and received information and ThunderStats shows no email in the statistics. After it has been corrected a database rebuild has to be forced (see the link above).

I'm going to close this issue. If you're are experiencing any problem, feel free to send me the debbugger report and I'll help you.
Thanks to all for your interest and help.

**Closed by micz** 2017-01-23 21:20 UTC
