### ISSUE TITLE
ThunderStats not compatible with Thunderbird 61+

### ISSUE THREAD

**Issue by daniel-barrows** [micz/ThunderStats#181] opened 2019-05-20 20:40 UTC
ThunderStats needs to be updated to work with Thunderbird version 61 and later. Note that the current maintainer, @micz, has [stated](https://github.com/micz/ThunderStats/issues/164#issuecomment-437705530) that they are not planning to work on this issue.

**Comment by micz** [comment] 2019-05-22 21:16
@cleidigh is helping working on compatibility for future releases, so stay tuned. :-)

**Comment by cleidigh** [comment] 2019-05-25 21:41
@daniel-barrows 
Indeed I am continuing to work on both of @micz 's extensions.
Because things are changing so much with Thunderbird I am targeting TB68 official Release
The intermediary betas are problematic to keep up with.

**Comment by cleidigh** [comment] 2019-08-26 03:39
@daniel-barrows 
FYI, just an update
I am getting close to an official release for Thunderbird 68
@cleidigh

**Comment by HeikoAdams** [comment] 2019-10-26 17:25
After installing version1.4.5-b3 and restarting thunderbird I got the following error when trying to open ThunderStats:
`XML-Verarbeitungsfehler: Nicht definierte Entität
Adresse: chrome://thunderstats/content/mzts-statstab.xhtml
Zeile Nr. 303, Spalte 37:`

**Comment by cleidigh** [comment] 2019-10-27 05:17
@HeikoAdams 
@daniel-barrows 
@micz 
I am still bouncing back and forth to get TS working for 60-70+
I just pushed b4 to the same branch
a lot of small things are fixed and some of the main functionality is working
- you have to hit the update button to get the first statistics
- the nonbusiness day editor is still disabled
- the new date picker still has quirks

**Comment by vitali-graf** [comment] 2019-10-27 10:51
With b4 is same error:
<img width="1070" alt="error-b4" src="https://user-images.githubusercontent.com/502287/67633429-0991e680-f8b0-11e9-967e-bf3b2d024bb0.png">

**Comment by RealRaven2000** [comment] 2019-10-27 11:20
Looks like this is a missing translation in the de locale?

**Comment by RealRaven2000** [comment] 2019-10-27 11:25
PS: I am on the German Babelzilla team for translating ThunderStats, but it hasn't been updated on Babelzilla for a while - @micz can you upload a new version or maybe share admin access with @cleidigh or me?

**Comment by cleidigh** [comment] 2019-10-27 20:49
@vitali-graf 
Thanks for the screen capture now understand what the issue is!

**Comment by cleidigh** [comment] 2019-10-27 22:12
okay.  my apologies!  I completely forgot I added a single new string for the new date picker , but had not gotten twenty translation issues yet, sorry
I will translate, and post b5 .  I am very interested to see if the other things I fixed are okay
but it's still not all done.

**Comment by cleidigh** [comment] 2019-10-27 22:56
b5  is uploaded
- added missing locale string for de, it and fr locales
- Reminder :  you have to press the update button to get the first statistics loaded
- no other fixes yet

**Comment by micz** [comment] 2019-10-28 09:22
> 
> 
> PS: I am on the German Babelzilla team for translating ThunderStats, but it hasn't been updated on Babelzilla for a while - @micz can you upload a new version or maybe share admin access with @cleidigh or me? (my handle on bz is RealRaven)

@RealRaven2000 I've added you as a mantainer on BabelZilla. @cleidigh Tell me your username if you wish to be added.
Thank you!

**Comment by cleidigh** [comment] 2019-11-01 05:45
@daniel-barrows 
@micz 
@vitali-graf 
@HeikoAdams 
I just posted Beta b6
it has a bunch of fixes and the nonbusiness days list is almost working new and Delete work

Any test feedback would be great.
@cleidigh

**Comment by dwarf007** [comment] 2019-11-12 11:38
Hello, thank you so much for working on this and having ported it to the latest Thunderbird.
With this extension beta I can now add custom identities again, however it looks to me as if they are not taken into account when computing the amount of Emails received.
A bit like what I reported in https://github.com/micz/ThunderStats/issues/164#issue-379301747

**Comment by dwarf007** [comment] 2019-11-12 11:41
One issue is that it actually looks like the custom identities are case sensitive, while they should probably not be.

**Comment by cleidigh** [comment] 2019-11-13 05:35
@dwarf007 
thanks for the feedback!  a lot of this is unfamiliar to me so this type of information is very helpful.
while I think the identities are clearly saved (we all agree on that), I think they are supposed to show up in the account selector of the main page.  I have the preference set for that but only the main identities show.  I think I can figure out where that went wrong.  I'm educating myself on that now.

The issue of case sensitivity seems to me fairly obvious and therefore I am wondering if there is a problem for making a case insensitive comparison.  I think I have the area of the code where this would occur: (in mdb)  @micz any comments?

```js
if (typeof mIdentity == "object") {
                mFrom += " left join messageattributes ma2 on ma2.messageID=m.id";
                let identitiesStr = "(" + mIdentity.ids.join() + ")";
                let identities_customStr = "(" + mIdentity.ids_custom.join() + ")";
                mWhere += "and ((ma.attributeID=" + mType_attribute + " AND ma2.attributeID=" + involves_attribute + " AND ma2.value in " + identitiesStr + ") OR ";
                mWhere += " (ma.attributeID=" + involves_attribute + " AND ma.value in " + identities_customStr + "))";

                console.debug('Identities1 '+identitiesStr);

```

**Comment by cleidigh** [comment] 2019-11-13 06:13
@micz 
I am stuck!
For  some time now I have believed something is not initialized related to identities.
as far as I can tell the set up and saving the preferences it's okay, the problem appears when loading the identities and trying to match ID to the custom identity e-mail:
```js
let identity_item = {};
                identity_item["email"] = identity;
                identity_item["fullName"] = "CustomID" + cid_prog;
                identity_item["id"] = miczThunderStatsDB.queryGetIdentityID(identity);
                identity_item["key"] = "__custom" + cid_prog;
                identity_item["custom"] = true;
                identity_item["account_key"] = this.custom_account_key;
                if (identity_item["id"]) {
                    cid_prog++;
                    this.identities[miczThunderStatsDB.queryGetIdentityID(identity)] = identity_item;
                    miczThunderStatsDB.identities_custom_ids.push(miczThunderStatsDB.queryGetIdentityID(identity));
                    miczThunderStatsDB.identities_custom_ids_mail.push(identity);
                    this.accounts[this.custom_account_key].identities.push(miczThunderStatsDB.queryGetIdentityID(identity));
                
```
the query get identity always returns false therefore the customer identity is never used.
I cannot figure out where that "initialization" occurs.
One thing I had to do with settings that did not make sense to me was that I had to
open the database to load the identities then close.  what does not make sense is how this was occurring before and I believe it's related to the problem here in terms of something in the database not getting initialized.
Help!
@cleidigh

**Comment by micz** [comment] 2019-11-13 09:23
On branch [v1.4.5-update](https://github.com/micz/ThunderStats/tree/v1.4.5-update)?

**Comment by micz** [comment] 2019-11-13 19:49
I've tried it on Thunderbird 71.0b2 and it loads the custom identities.
Consider that if you add a custom identity you need to have at least one mail indexed for that email address to get the identity id. Otherwise the custom identity is ignored.

**Comment by cleidigh** [comment] 2019-11-13 19:59
Excellent! Thanks
it just didn't make sense to me .
I have to come up with a way to test this.  I think I can copy some e-mails that will be like custom identities.
I have to describe the initialization issue better because I still think that's without explanation.
Let me confirm that The other things going and then I'll address that.

**Comment by micz** [comment] 2019-11-13 20:17
This extension works querying the internal Thunderbird database that is populated by Thunderbird when it indexes the emails.
Thunderbird adds an identity for every email address it manages.
If the user adds a custom identity, in order to use it in a query, ThunderStats needs to find its identity_id. If Thunderbird has never seen that address, there no identity_id for it and ThunderStats can not use it in the queries.

**Comment by cleidigh** [comment] 2019-11-14 05:44
@micz  okay I think I understand the database little better.  I still have to clearly identify the other issue.
I was hoping to do that today, but my vent almost killed me so I lost a bunch of time, but at least it did not succeed!
Anyway, good news all around... once I had at least one e-mail for the customer identity it was okay.
I believe I have also fixed the case sensitivity. @dwarf007 .  I can test and confirm this for the custom identities now, but I have not yet proved case insensitivity for all identities, But I should be able to prove that tomorrow.

I still have several items to fix and cleanup , but I think were close.

if anybody has feedback on b7 that would be great.  We appear to have a difference in that @dwarf007 reported  custom identity problems ,but I do.know which version.

I am going to create a "punch list" issue with the remaining items to fix.  @micz I will be sure I capture the prior comments you made on several issues like the debugger (which I already fixed)

Thanks for everybody's help looking at the beta.

**Comment by cleidigh** [comment] 2019-11-15 01:58
@micz 
@daniel-barrows 
@dwarf007 
B8 attempts to also fix case sensitivity issue with the main identities.
I have to figure out some more tests, but I think I may have part or all of it solved.
First I made all of the identity ID queries case insensitive because as far as I can tell
the database treats those without case sensitivity.
//returns the id of an identity from its email
    queryGetIdentityID: function(email) {
        // cleidigh - e-mail id queries should be case insensitive db expects normalized to lowercase
        let mWhere = 'value="' + email.toLowerCase() + '" LIMIT 1';
        let rows = this.querySelect("id", "identities", mWhere);
        if (rows.length > 0) {
            return rows[0][0];
        } else {
            return false;
        }
    },

I also converted the e-mail to lowercase within ThunderStats .
I made an account with mixed case as @daniel-barrows did in issue #180 
by inspection it looks like Thunderbird normalizes the incoming addresses.
Now that TS does as well, I see counts even with the mixed case.
What I still need to try and test is an incoming e-mail with the mixed case e-mail.
I have to make or find the client which will do that.

**Comment by dwarf007** [comment] 2019-11-15 10:27
aoutch! Although beta 6 worked for me on Thunderbird 60.9.1 (64bit), beta 7 as well, now beta 8 does no longer work :-(
At the top "Choose Account" drop-down list is now empty, also in the settings the "Startup Account" drop-down list is empty, and for custom identities the "Account" drop-down list is empty

**Comment by cleidigh** [comment] 2019-11-15 20:06
@dwarf007 
Arrg!  my plan was not to go backwards! Crumbs.  I just double checked because I couldn't remember which version I have for 60, we match.  My 60.9.1 is 32b but I doubt that's the issue.
b8 has very targeted changes for the non-case sensitivity.  It sounds like a preferences issue.  Can you check the debug console and TS debug output?
I may have to add some more debugs and since We have different results.
Hopefully I can think of something useful for b9
One other thing I would be curious about - if you go back to 7 does everything look good again?

**Comment by dwarf007** [comment] 2019-11-15 23:18
After having the problems with b8, it worked ok again when I moved back to b7.
Attached the debug outputs:
<img width="972" alt="DebugConsoleTS" src="https://user-images.githubusercontent.com/2540393/68982194-53fae900-0806-11ea-8ac8-502c0a637836.png">
and:
[TS_DebugLogs.txt](https://github.com/micz/ThunderStats/files/3853492/TS_DebugLogs.txt)

**Comment by cleidigh** [comment] 2019-11-15 23:33
@dwarf007 
Excellent, this is exactly what I need a defined error and where I would expect it!
Now I have to figure out why I cannot reproduce it. 
Thanks again...

**Comment by cleidigh** [comment] 2019-11-18 05:33
@dwarf007 
I didn't realize you were on OS X, that's a difference in our testing before.  I just tested b8 on my OS X Mojave and so far no errors.  Testing/Fixing on OS X is going to be very tricky for me given my dictation software requirement it's really slow so bear with me.
I'm going to some more debug.

**Comment by cleidigh** [comment] 2019-11-20 05:24
All
I just posted b9 with just a single difference, I removed the case sensitivity fix for the main  identities
I think that maybe a possible problem, unfortunately I still cannot reproduce the exact error on OS X.
I'm hoping to reduce the scope.
Feedback appreciated!

**Comment by dwarf007** [comment] 2019-11-21 10:29
@cleidigh : I have the exact same problem with b9, then the one I had with b8. Only b7 works OK

**Comment by cleidigh** [comment] 2019-11-24 05:46
@dwarf007 
I have been testing over and over and I really don't know what's going on.  There is opacity to the database which may be the problem with capitalization.  I think having fixed the custom identities to be case insensitive is an improvement. I think I should try and clean up and make a Release.
I don't think I should hold that up.

**Comment by cleidigh** [comment] 2019-11-28 00:33
uploaded b10
should deal with capitalization as in b7
lots affixes for nonbusiness days

**Comment by dwarf007** [comment] 2019-11-28 10:41
@cleidigh for me, it is only b7 that works. 
Also b10 does not list the accounts.
![image](https://user-images.githubusercontent.com/2540393/69799665-056d2780-11d4-11ea-8f97-c95bc24bf627.png)

**Comment by micz** [comment] 2019-11-28 10:44
May you open the Error Console (CTRL+SHIFT+J on windows), clear the log, then open the ThunderStats tab and check if there is any javascript error?
Thanks.

**Comment by cleidigh** [comment] 2019-12-03 01:25
b11 reverts back to the capitalization handling in b7
there is some more debug as well as fixes for nonbusiness days
hopefully this at least gets us to where we were

**Comment by cleidigh** [comment] 2019-12-07 04:10
b 12 should be fully functional
I intend to clean up and Release

**Comment by cleidigh** [comment] 2019-12-09 06:41
@micz 
All
I have posted b14
Unless there is a surprise I will be releasing tomorrow.
I know there's quirks , but I think we need to get it out so we get more feedback.
I tested with 72.0b1 and it basically parks budget has some UI oddities.
@cleidigh

**Comment by dwarf007** [comment] 2019-12-09 10:21
> May you open the Error Console (CTRL+SHIFT+J on windows), clear the log, then open the ThunderStats tab and check if there is any javascript error?


![image](https://user-images.githubusercontent.com/2540393/70427994-058fe180-1a76-11ea-9cd8-f81dade37d0a.png)

**Comment by cleidigh** [comment] 2019-12-09 21:06
@dwarf007 
Thanks for looking at b14.  There her two confusing things here, 1 I cannot reproduce, 2 The error you have above is the same as before and it references a file error where no file operation is being done.
I keep thinking it might be a profile issue. Can you try a new profile starting out with just a single e-mail address and identity then add a custom identity.  

I will also try to think of some more debugging output that might help.  I am probably still going to go ahead and do the Release so perhaps we can get some more people finding things.

**Comment by cleidigh** [comment] 2019-12-17 03:09
b15 has been posted for Release

**Comment by cleidigh** [comment] 2020-01-11 19:52
just got released...

**Comment by Somnialamment** [comment] 2020-05-05 17:58
Hi there!. I am having the same issue with the Account Selection combo... I read that you need a b7 or something like these but this is for OS X versions... i have a Windows SO so wich version i need to download so i can select the accounts that i need to analyze??

Thanks in advance!

**Comment by micz** [comment] 2024-05-03 20:48
I know it has been many years of silence, but finally work on ThunderStats has resumed, as described [here](https://github.com/micz/ThunderStats/issues/195).

I'm targeting Thunderbird 128+; therefore, I’m closing this issue.

**Closed by micz** 2024-05-03 20:48 UTC
